twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
            documents: '%documents%'
            pageimages: '%pageimages%'
            dogimages: '%dogimages%'
            profileimages: '%profileimages%'
            mainslider: '%mainslider%'

when@test:
    twig:
        strict_variables: true
